apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
      - name: student-app
        image: student-app:latest
        imagePullPolicy: Never # Tells K8s to use the local image you just built
        ports:
        - containerPort: 8081